# 配置文件编写请参考 https://github.com/SmallPeaches/DanmakuRender 

# 渲染参数
render:
  # 同时执行的渲染任务数，默认1，若渲染时CPU和GPU使用都低于80%可以调高这个，一般情况下设置应该小于5
  # 特别提示：如果渲染一个CPU或者显卡占用都很高，调高这个反而有副作用！
  nrenders: 1
  
  # 渲染输出文件夹，默认为空（在录制输出文件夹后面加上“带弹幕版”）
  output_dir: ~

  # 生成的视频文件格式，默认mp4
  format: mp4
  
  # 硬件解码参数，默认由FFmpeg自动判断，如果出现问题可以设为空
  hwaccel_args: [-hwaccel, auto]

  # 视频编码器，NVIDIA设置为h264_nvenc，AMD设置为h264_amf，CPU设置为libx264
  vencoder: h264_nvenc

  # 视频编码器参数，默认恒定码率15Mbps
  vencoder_args: [-b:v, 15M]

  # 音频编码器
  aencoder: aac

  # 音频编码器参数，默认恒定码率320Kbps
  aencoder_args: [-b:a, 320K]

  # 输出重缩放，会把输出重缩放到指定分辨率，可以设置为'3840x2160'用于在B站传伪4K保证清晰度
  output_resize: ~

# 上传参数
uploader:
  nuploaders: 1
