# FFprobe 可执行程序地址，为空自动搜索
ffprobe: ~
# FFmpeg 可执行程序地址，为空自动搜索
ffmpeg: ~

# 录制参数
downloader:
  # 录制输出文件夹，设置为空则使用主播名称作为文件夹
  output_dir: ./直播回放

  # 录制文件名称格式，可使用关键字替换，默认效果：飞天狙想要努力变胖-2023年3月1日20点30分，注意这里不能含有冒号，斜杠等非法字符！！
  output_name: '{STREAMER}-{YEAR}年{MONTH}月{DAY}日{HOUR}点{MINUTE}分'

  # 录播分段时间（秒），默认一个小时
  segment: 3600

  # 是否录制弹幕
  danmaku: True

  # 是否录制直播流
  video: True

  # 启动自动渲染
  auto_render: True

  # 延迟下播计时（分钟）
  end_cnt: 1

  # 默认分辨率，如果程序无法正常判断流的分辨率可以使用以下参数强行指定
  resolution: [1920,1080]

  # 录制视频的格式，默认mp4，如果经常遇到文件损坏播不了可以选择ts
  vid_format: mp4

  # 录制程序引擎，只能是ffmpeg
  engine: ffmpeg

  # 直播流CDN选项
  # 对于虎牙直播，此项可选al, tx, hw等cdn服务器的缩写，默认al
  # 对于B站，此项可选0-n表示不同的cdn服务器，默认为0
  # 斗鱼和抖音暂时没用
  flow_cdn: ~

  # ffmpeg http参数
  ffmpeg_stream_args: [-fflags,+discardcorrupt,-reconnect,'1',-rw_timeout,'10000000',
                        '-analyzeduration','15000000',
                        '-probesize','50000000',
                        '-thread_queue_size', '16']
  
  # 关闭编码过慢自动重启功能，默认false
  disable_lowspeed_interrupt: False
  
  # 以下是弹幕录制参数

  # 弹幕行距，默认6
  margin: 6

  # 指定弹幕占屏幕的最大比例（即屏幕上半部分有多少可以用来显示弹幕），默认为0.4
  dmrate: 0.4

  # 指定弹幕字体，默认为微软雅黑字体(Microsoft YaHei)
  font: Microsoft YaHei

  # 指定弹幕字体大小，默认为36
  fontsize: 36 

  # 指定过量弹幕的处理方法，
  # 可选ignore（忽略过量弹幕）或者override（强行叠加弹幕），默认override
  overflow_op: override

  # 指定单条弹幕持续时间（秒），默认为16
  dmduration: 16

  # 指定弹幕不透明度，默认为0.8
  opacity: 0.8

  # 使用自适应弹幕大小（会让把设置的弹幕大小按1080P标准缩放）
  auto_fontsize: True

  # 弹幕描边颜色(6位十六进制)
  outlinecolor: 000000

  # 弹幕描边宽度
  outlinesize: 1.0
  
  # 弹幕延迟补偿（秒），一般情况下弹幕比视频慢，设置这个强行把弹幕提前，不同直播间不一样
  dm_delay_fixed: 3.0

  # 弹幕录制程序自动重启间隔（在没人发弹幕的时候会定时重启，保证录制正常，默认300秒，0关闭）
  dm_auto_restart: 300

# 渲染参数
render:
  # 渲染输出文件夹，默认为空（在录制输出文件夹后面加上“带弹幕版”）
  output_dir: ~

  # 生成的视频文件格式，默认mp4
  format: mp4

  # 渲染引擎，可选ffmpeg（纯ffmpeg渲染）或者python（Python PIL作为弹幕的图像渲染器，ffmpeg作为视频编码器）
  engine: ffmpeg

  # 硬件解码参数，NVIDIA显卡默认使用cuda硬件解码器，AMD显卡或者CPU设为空
  hwaccel_args: [-hwaccel,cuda,-noautorotate]

  # 视频编码器，NVIDIA设置为h264_nvenc，AMD设置为h264_amf，CPU设置为libx264
  vencoder: h264_nvenc

  # 视频编码器参数，默认恒定码率15Mbps，防止B站DASH技术导致音画不同步(GOP=5s)
  vencoder_args: [-b:v,15M, -g, 300, -keyint_min, 300, -sc_threshold, 0]

  # 音频编码器
  aencoder: aac

  # 音频编码器参数，默认恒定码率320Kbps
  aencoder_args: [-b:a,320K]

  # 输出重缩放，会把输出重缩放到指定分辨率，可以设置为'3840x2160'用于在B站传伪4K保证清晰度
  output_resize: ~

  # 以下参数只适用于python渲染器
  # 渲染线程数（单个渲染器使用的进程数量），默认2
  nproc: 2

  # 渲染管道缓冲区大小（MB）
  bufsize: 100

  # 弹幕重排序
  danmaku_resort: False

# 自动上传参数
uploader:
  # 上传目标（目前只有B站）
  bilibili:
    # 上传引擎，目前只能选biliuprs
    engine: biliuprs

    # biliup-rs可执行文件地址
    biliup: tools/biliup.exe

    # 登录信息保存的cookies路径，默认<上传器名字>.json
    cookies: ~

    # 上传的视频最短长度，小于此长度的视频会被自动过滤，默认五分钟
    min_length: 300

    # 以下参数来自biliuprs，详细内容可以参考 https://biliup.github.io/biliup-rs/index.html
    # 上传线路
    line: bda2

    # 上传线程数
    limit: 3

    # 是否为转载视频 1-自制 2-转载
    copyright: 1

    # 转载来源
    source: ''

    # 分区号，分区参考 https://biliup.github.io/tid-ref.html
    tid: 65

    # 封面
    cover: ''

    # 标题，可以使用关键字替换
    # {STREAMER}主播名称，{TITLE}标题，{YEAR}年，{MONTH}月，{DAY}日，{HAS_DANMU}“带弹幕版”这几个字，{URL}直播间链接
    # 默认的例子：[飞天狙想要努力变胖/直播回放] 晚上七点半比赛 2023年2月24日 （带弹幕版）
    title: '[{STREAMER}/直播回放] {TITLE} {YEAR}年{MONTH}月{DAY}日 {HAS_DANMU}'

    # 简介，可以使用关键字替换
    desc: "{STREAMER}: {URL} \n直播回放 {TITLE} {YEAR}年{MONTH}月{DAY}日 {HAS_DANMU} \nPowered by DanmakuRender \nhttps://github.com/SmallPeaches/DanmakuRender"
    
    # 动态内容，可以使用关键字替换
    dynamic: ''

    # 互动视频
    interactive: 0

    # 标签（一定要有！多个标签逗号分割）
    tag: '直播回放'

    # 延迟发布，单位秒
    dtime: 0

    # 是否开启杜比音效? 0-关闭 1-开启
    dolby: 0

    # 允许转载? 0-允许转载，1-禁止转载
    no_reprint: 1

    # 是否开启充电? 0-关闭 1-开启
    open_elec: 1


